### ISSUE TITLE
mikusore.jpgのライセンス大丈夫？

### ISSUE THREAD

**Issue by c-bata** [kosen10s/i#1]

**Comment by denari** [comment]
だいじょばない気がした

**Comment by denari** [comment]
とりあえず Good bye MIKU-SAN したけど代替案なんかないかな〜

**Comment by c-bata** [comment]
vpsとかにbasic認証かけて置いとくぐらいかな
dropboxのpublicフォルダでも、URL教えないかぎり見れないからいいと思うけど
